2021-07-08 06:59:50.734223: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-07-08 06:59:53.933985: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-07-08 06:59:53.946033: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-07-08 06:59:53.946102: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (9a22d0e2e7c1): /proc/driver/nvidia/version does not exist
2021-07-08 06:59:53.946666: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-08 06:59:53.952766: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2299995000 Hz
2021-07-08 06:59:53.953086: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56089ee1af40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-07-08 06:59:53.953122: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:201: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
2021-07-08 07:00:05.342168: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.58.211.250:8470}
2021-07-08 07:00:05.342227: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:31036}
2021-07-08 07:00:05.360314: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.58.211.250:8470}
2021-07-08 07:00:05.360381: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:31036}
2021-07-08 07:00:05.361128: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:405] Started server with target: grpc://localhost:31036
Model: "res_net"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
sequential_6 (Sequential)    (None, 40, 40, 64)        29024     
_________________________________________________________________
sequential_27 (Sequential)   multiple                  269411    
_________________________________________________________________
sequential_54 (Sequential)   multiple                  1362052   
_________________________________________________________________
sequential_75 (Sequential)   multiple                  16572803  
_________________________________________________________________
sequential_114 (Sequential)  multiple                  7917958   
_________________________________________________________________
global_avg_pool_16 (GlobalAv multiple                  0         
_________________________________________________________________
dropout (Dropout)            multiple                  0         
_________________________________________________________________
dense (Dense)                multiple                  2049000   
=================================================================
Total params: 28,200,248
Trainable params: 28,146,984
Non-trainable params: 53,264
_________________________________________________________________
2021-07-08 07:00:54.958280: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Load learner at epoch 174 from /content/drive/MyDrive/models/ImageNet-107-3/ckpt
15:00:57 Start training
Epoch 175/200
15:07:42 train - loss: 2.3121, acc: 0.6810
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py:601: get_next_as_optional (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Iterator.get_next_as_optional()` instead.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py:601: get_next_as_optional (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Iterator.get_next_as_optional()` instead.
WARNING:tensorflow:Model was constructed with shape (None, 160, 160, 3) for input Tensor("sequential_1_input:0", shape=(None, 160, 160, 3), dtype=float32), but it was called on an input with incompatible shape (None, 224, 224, 3).
WARNING:tensorflow:Model was constructed with shape (None, 160, 160, 3) for input Tensor("sequential_1_input:0", shape=(None, 160, 160, 3), dtype=float32), but it was called on an input with incompatible shape (None, 224, 224, 3).
WARNING:tensorflow:Model was constructed with shape (None, 160, 160, 3) for input Tensor("sequential_1/sequential_input:0", shape=(None, 160, 160, 3), dtype=float32), but it was called on an input with incompatible shape (None, 224, 224, 3).
WARNING:tensorflow:Model was constructed with shape (None, 160, 160, 3) for input Tensor("sequential_1/sequential_input:0", shape=(None, 160, 160, 3), dtype=float32), but it was called on an input with incompatible shape (None, 224, 224, 3).
WARNING:tensorflow:Model was constructed with shape (None, 80, 80, 32) for input Tensor("sequential_3/sequential_2_input:0", shape=(None, 80, 80, 32), dtype=bfloat16), but it was called on an input with incompatible shape (None, 112, 112, 32).
WARNING:tensorflow:Model was constructed with shape (None, 80, 80, 32) for input Tensor("sequential_3/sequential_2_input:0", shape=(None, 80, 80, 32), dtype=bfloat16), but it was called on an input with incompatible shape (None, 112, 112, 32).
WARNING:tensorflow:Model was constructed with shape (None, 80, 80, 32) for input Tensor("sequential_5/sequential_4_input:0", shape=(None, 80, 80, 32), dtype=bfloat16), but it was called on an input with incompatible shape (None, 112, 112, 32).
WARNING:tensorflow:Model was constructed with shape (None, 80, 80, 32) for input Tensor("sequential_5/sequential_4_input:0", shape=(None, 80, 80, 32), dtype=bfloat16), but it was called on an input with incompatible shape (None, 112, 112, 32).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 64) for input Tensor("bottleneck/sequential_14/sequential_13_input:0", shape=(None, 40, 40, 64), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 64).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 64) for input Tensor("bottleneck/sequential_14/sequential_13_input:0", shape=(None, 40, 40, 64), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 64).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 64) for input Tensor("bottleneck/sequential_14/sequential_13/conv2d_8_input:0", shape=(None, 40, 40, 64), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 64).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 64) for input Tensor("bottleneck/sequential_14/sequential_13/conv2d_8_input:0", shape=(None, 40, 40, 64), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 64).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 64) for input Tensor("bottleneck/sequential_7/conv2d_3_input:0", shape=(None, 40, 40, 64), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 64).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 64) for input Tensor("bottleneck/sequential_7/conv2d_3_input:0", shape=(None, 40, 40, 64), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 64).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 64) for input Tensor("bottleneck/sequential_9/sequential_8_input:0", shape=(None, 40, 40, 64), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 64).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 64) for input Tensor("bottleneck/sequential_9/sequential_8_input:0", shape=(None, 40, 40, 64), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 64).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 256) for input Tensor("conv2d_9_input:0", shape=(None, 40, 40, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 256).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 256) for input Tensor("conv2d_9_input:0", shape=(None, 40, 40, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 256).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 64) for input Tensor("sequential_16_input:0", shape=(None, 40, 40, 64), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 64).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 64) for input Tensor("sequential_16_input:0", shape=(None, 40, 40, 64), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 64).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 256) for input Tensor("conv2d_14_input:0", shape=(None, 40, 40, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 256).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 256) for input Tensor("conv2d_14_input:0", shape=(None, 40, 40, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 256).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 64) for input Tensor("sequential_22_input:0", shape=(None, 40, 40, 64), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 64).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 64) for input Tensor("sequential_22_input:0", shape=(None, 40, 40, 64), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 64).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 256) for input Tensor("bottleneck_3/sequential_35/average_pooling2d_input:0", shape=(None, 40, 40, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 256).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 256) for input Tensor("bottleneck_3/sequential_35/average_pooling2d_input:0", shape=(None, 40, 40, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 256).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 256) for input Tensor("bottleneck_3/sequential_35/sequential_34/conv2d_24_input:0", shape=(None, 20, 20, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 256).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 256) for input Tensor("bottleneck_3/sequential_35/sequential_34/conv2d_24_input:0", shape=(None, 20, 20, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 256).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 256) for input Tensor("bottleneck_3/sequential_28/conv2d_19_input:0", shape=(None, 40, 40, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 256).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 256) for input Tensor("bottleneck_3/sequential_28/conv2d_19_input:0", shape=(None, 40, 40, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 256).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 128) for input Tensor("bottleneck_3/sequential_30/sequential_29_input:0", shape=(None, 40, 40, 128), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 128).
WARNING:tensorflow:Model was constructed with shape (None, 40, 40, 128) for input Tensor("bottleneck_3/sequential_30/sequential_29_input:0", shape=(None, 40, 40, 128), dtype=bfloat16), but it was called on an input with incompatible shape (None, 56, 56, 128).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 512) for input Tensor("conv2d_25_input:0", shape=(None, 20, 20, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 512).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 512) for input Tensor("conv2d_25_input:0", shape=(None, 20, 20, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 512).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 128) for input Tensor("sequential_37_input:0", shape=(None, 20, 20, 128), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 128).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 128) for input Tensor("sequential_37_input:0", shape=(None, 20, 20, 128), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 128).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 512) for input Tensor("conv2d_30_input:0", shape=(None, 20, 20, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 512).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 512) for input Tensor("conv2d_30_input:0", shape=(None, 20, 20, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 512).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 128) for input Tensor("sequential_43_input:0", shape=(None, 20, 20, 128), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 128).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 128) for input Tensor("sequential_43_input:0", shape=(None, 20, 20, 128), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 128).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 512) for input Tensor("conv2d_35_input:0", shape=(None, 20, 20, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 512).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 512) for input Tensor("conv2d_35_input:0", shape=(None, 20, 20, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 512).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 128) for input Tensor("sequential_49_input:0", shape=(None, 20, 20, 128), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 128).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 128) for input Tensor("sequential_49_input:0", shape=(None, 20, 20, 128), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 128).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 512) for input Tensor("bottleneck_10/sequential_83/average_pooling2d_2_input:0", shape=(None, 20, 20, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 512).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 512) for input Tensor("bottleneck_10/sequential_83/average_pooling2d_2_input:0", shape=(None, 20, 20, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 512).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 512) for input Tensor("bottleneck_10/sequential_83/sequential_82/conv2d_61_input:0", shape=(None, 10, 10, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 512).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 512) for input Tensor("bottleneck_10/sequential_83/sequential_82/conv2d_61_input:0", shape=(None, 10, 10, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 512).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 512) for input Tensor("bottleneck_10/sequential_76/conv2d_56_input:0", shape=(None, 20, 20, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 512).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 512) for input Tensor("bottleneck_10/sequential_76/conv2d_56_input:0", shape=(None, 20, 20, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 512).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 256) for input Tensor("bottleneck_10/sequential_78/sequential_77_input:0", shape=(None, 20, 20, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 256).
WARNING:tensorflow:Model was constructed with shape (None, 20, 20, 256) for input Tensor("bottleneck_10/sequential_78/sequential_77_input:0", shape=(None, 20, 20, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 28, 28, 256).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("conv2d_62_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("conv2d_62_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 256) for input Tensor("sequential_85_input:0", shape=(None, 10, 10, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 256).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 256) for input Tensor("sequential_85_input:0", shape=(None, 10, 10, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 256).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("conv2d_67_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("conv2d_67_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 256) for input Tensor("sequential_91_input:0", shape=(None, 10, 10, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 256).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 256) for input Tensor("sequential_91_input:0", shape=(None, 10, 10, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 256).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("conv2d_72_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("conv2d_72_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 256) for input Tensor("sequential_97_input:0", shape=(None, 10, 10, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 256).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 256) for input Tensor("sequential_97_input:0", shape=(None, 10, 10, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 256).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("conv2d_77_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("conv2d_77_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 256) for input Tensor("sequential_103_input:0", shape=(None, 10, 10, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 256).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 256) for input Tensor("sequential_103_input:0", shape=(None, 10, 10, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 256).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("conv2d_82_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("conv2d_82_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 256) for input Tensor("sequential_109_input:0", shape=(None, 10, 10, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 256).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 256) for input Tensor("sequential_109_input:0", shape=(None, 10, 10, 256), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 256).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("bottleneck_7/sequential_62/average_pooling2d_1_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("bottleneck_7/sequential_62/average_pooling2d_1_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 5, 5, 1024) for input Tensor("bottleneck_7/sequential_62/sequential_61/conv2d_45_input:0", shape=(None, 5, 5, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 7, 7, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 5, 5, 1024) for input Tensor("bottleneck_7/sequential_62/sequential_61/conv2d_45_input:0", shape=(None, 5, 5, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 7, 7, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("bottleneck_7/sequential_55/conv2d_40_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 1024) for input Tensor("bottleneck_7/sequential_55/conv2d_40_input:0", shape=(None, 10, 10, 1024), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 1024).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 512) for input Tensor("bottleneck_7/sequential_57/sequential_56_input:0", shape=(None, 10, 10, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 512).
WARNING:tensorflow:Model was constructed with shape (None, 10, 10, 512) for input Tensor("bottleneck_7/sequential_57/sequential_56_input:0", shape=(None, 10, 10, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 14, 14, 512).
WARNING:tensorflow:Model was constructed with shape (None, 5, 5, 2048) for input Tensor("conv2d_46_input:0", shape=(None, 5, 5, 2048), dtype=bfloat16), but it was called on an input with incompatible shape (None, 7, 7, 2048).
WARNING:tensorflow:Model was constructed with shape (None, 5, 5, 2048) for input Tensor("conv2d_46_input:0", shape=(None, 5, 5, 2048), dtype=bfloat16), but it was called on an input with incompatible shape (None, 7, 7, 2048).
WARNING:tensorflow:Model was constructed with shape (None, 5, 5, 512) for input Tensor("sequential_64_input:0", shape=(None, 5, 5, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 7, 7, 512).
WARNING:tensorflow:Model was constructed with shape (None, 5, 5, 512) for input Tensor("sequential_64_input:0", shape=(None, 5, 5, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 7, 7, 512).
WARNING:tensorflow:Model was constructed with shape (None, 5, 5, 2048) for input Tensor("conv2d_51_input:0", shape=(None, 5, 5, 2048), dtype=bfloat16), but it was called on an input with incompatible shape (None, 7, 7, 2048).
WARNING:tensorflow:Model was constructed with shape (None, 5, 5, 2048) for input Tensor("conv2d_51_input:0", shape=(None, 5, 5, 2048), dtype=bfloat16), but it was called on an input with incompatible shape (None, 7, 7, 2048).
WARNING:tensorflow:Model was constructed with shape (None, 5, 5, 512) for input Tensor("sequential_70_input:0", shape=(None, 5, 5, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 7, 7, 512).
WARNING:tensorflow:Model was constructed with shape (None, 5, 5, 512) for input Tensor("sequential_70_input:0", shape=(None, 5, 5, 512), dtype=bfloat16), but it was called on an input with incompatible shape (None, 7, 7, 512).
15:08:27 valid - loss: 1.0045, acc: 0.7863, acc5: 0.9450
Epoch 176/200
15:12:25 train - loss: 2.3026, acc: 0.6832
Save learner to /content/drive/MyDrive/models/ImageNet-107-3/ckpt
15:12:38 valid - loss: 1.0026, acc: 0.7886, acc5: 0.9459
Epoch 177/200
15:16:34 train - loss: 2.2950, acc: 0.6856
15:16:48 valid - loss: 0.9988, acc: 0.7873, acc5: 0.9452
Epoch 178/200
15:20:40 train - loss: 2.2851, acc: 0.6882
Save learner to /content/drive/MyDrive/models/ImageNet-107-3/ckpt
15:20:58 valid - loss: 1.0044, acc: 0.7869, acc5: 0.9458
Epoch 179/200
15:24:46 train - loss: 2.2787, acc: 0.6895
15:25:00 valid - loss: 0.9933, acc: 0.7899, acc5: 0.9457
Epoch 180/200
15:28:53 train - loss: 2.2678, acc: 0.6924
Save learner to /content/drive/MyDrive/models/ImageNet-107-3/ckpt
15:29:10 valid - loss: 0.9856, acc: 0.7921, acc5: 0.9478
Epoch 181/200
15:32:58 train - loss: 2.2610, acc: 0.6939
15:33:13 valid - loss: 0.9875, acc: 0.7903, acc5: 0.9468
Epoch 182/200
15:37:04 train - loss: 2.2547, acc: 0.6960
Save learner to /content/drive/MyDrive/models/ImageNet-107-3/ckpt
15:37:22 valid - loss: 0.9795, acc: 0.7919, acc5: 0.9475
Epoch 183/200
15:41:09 train - loss: 2.2464, acc: 0.6982
15:41:23 valid - loss: 0.9747, acc: 0.7939, acc5: 0.9481
Epoch 184/200
15:45:15 train - loss: 2.2387, acc: 0.7001
Save learner to /content/drive/MyDrive/models/ImageNet-107-3/ckpt
15:45:32 valid - loss: 0.9721, acc: 0.7957, acc5: 0.9485
Epoch 185/200
15:49:20 train - loss: 2.2311, acc: 0.7021
15:49:35 valid - loss: 0.9657, acc: 0.7970, acc5: 0.9488
Epoch 186/200
15:53:25 train - loss: 2.2255, acc: 0.7032
Save learner to /content/drive/MyDrive/models/ImageNet-107-3/ckpt
15:53:43 valid - loss: 0.9630, acc: 0.7970, acc5: 0.9495
Epoch 187/200
15:57:31 train - loss: 2.2200, acc: 0.7046
15:57:45 valid - loss: 0.9620, acc: 0.7978, acc5: 0.9487
Epoch 188/200
16:01:37 train - loss: 2.2127, acc: 0.7070
Save learner to /content/drive/MyDrive/models/ImageNet-107-3/ckpt
16:01:54 valid - loss: 0.9549, acc: 0.7990, acc5: 0.9500
Epoch 189/200
16:05:42 train - loss: 2.2063, acc: 0.7082
16:05:56 valid - loss: 0.9552, acc: 0.7997, acc5: 0.9503
Epoch 190/200
16:09:47 train - loss: 2.2020, acc: 0.7096
Save learner to /content/drive/MyDrive/models/ImageNet-107-3/ckpt
16:10:05 valid - loss: 0.9502, acc: 0.8005, acc5: 0.9502
Epoch 191/200
16:13:53 train - loss: 2.1991, acc: 0.7105
16:14:07 valid - loss: 0.9492, acc: 0.8010, acc5: 0.9506
Epoch 192/200
Traceback (most recent call last):
  File "107.py", line 235, in <module>
    save_freq=2, callbacks=[DropPathRateScheduleV2()])
  File "/content/hanser/hanser/train/learner.py", line 242, in fit
    self._run_epoch(self._train_it, steps_per_epoch, cbks, 'train')
  File "/content/hanser/hanser/train/learner.py", line 344, in _run_epoch
    state['metrics'][name] = metric.result().numpy()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1063, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1029, in _numpy
    return self._numpy_internal()
KeyboardInterrupt
